version: '3.8'

services:
  back-end:
    image: softy-pinko-back-end:task4
    build: ./back-end
    ports:
      - "5252:5252"
  
  front-end:
    image: softy-pinko-front-end:task4
    build: ./front-end
    ports:
      - "9000:9000"
    depends_on:
      - back-end
