version: '3.8'

services:
  proxy:
    image: softy-pinko-proxy:task5
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
  
  front-end:
    image: softy-pinko-front-end:task5
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - back-end

  back-end:
    image: softy-pinko-back-end:task5
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
  
  
  
 
